[connections.my_database]
    type="sql"
    dialect="mysql"
    username="root"
    password="root1234"
    host="localhost" # IP or URL
    port=3306 # Port number
    database="newdbone" # Database name